---
title: "Figures for conference paper"
author: "DARS"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
library(kableExtra)
library(DiagrammeR)

knitr::opts_chunk$set(echo = FALSE)
theme_set(theme_light())

load("Output/catalogues_best_model.RDATA")
load("Output/data_pillar_1.Rdata")
load("Output/d_text.RDATA")
load("Output/df_logLike_catalogue.RDATA")
load("Output/CV.RDATA")

output_folder <- "Conference/Figures"
plot_width <- 6
plot_height <- plot_width / 1.6 
```

```{r TM}
d     <- best_lda
gamma <- best_lda$Gamma
beta  <- best_lda$Beta
```

```{r student_data}
set.seed(2019)

student_data <- d_transcript_augmented %>%
  
  select(`Student ID`, `Course ID`, `Academic Year`, Period = period_numerical, Grade) %>%
  
  mutate(`Student ID` = ((as.numeric(`Student ID`) + 2019) * as.numeric(`Student ID`)) %% 1e5  %>% as.character) %>% # anonymization
  
  sample_n(10) %>%
  
  arrange(`Academic Year`) %>%
  
  print
```

```{r}
course_data <- d_text$catalogues %>% 
  
  slice(50005:50014) %>%
  
  select(`Course ID`, `Course Title`, Department = department, word) 
```

# Student data

```{r fig_student_data}
student_data %>% 
  kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/student_data.pdf"))
```

# Course data

```{r fig_course_data}
course_data %>%
  kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/course_data.pdf"))
```

# Flow chart

```{r}
grViz("digraph flowchart{

      fontname = Helvetica
      size = 15

      node [fontname = Helvetica, shape = rectangle, style = filled, color = black, fillcolor = white]

      edge [fontname = Helvetica, decorate = TRUE]

      subgraph cluster_data {
      label = 'Data';
      style = filled;
		  color = lightgrey;
		  node [shape = cylinder];
      CD [label = 'Course Data']
      SD [label = 'Student Data']
      }

      subgraph cluster_input_user {
      label = 'User Input';
      style = filled;
		  color = coral;

      ID [label = 'Student ID']
      KW [label = 'Selected Key Words']
      CS [label = 'Selected Courses']
      }

      subgraph cluster_model_fitting{
      label = 'Model Fitting';
      style = filled;
		  color = LavenderBlush;

      TE [label = 'Topic Expertise']
      AP [label = 'Academic Performance']

      PM [label = 'Predictive Models']
      x1 [shape = circle, width = .01, height = .01, label = '']
      TM [label = 'Topic Model']

      }

      subgraph cluster_inter_last{
      label = 'Intermediate Results';
      style = filled;
		  color = Tan;

      GP [label = 'Grade Prediction']
      AI [label = 'Student´s Academic Interests']
      }

      # Ouput
      subgraph cluster_ouput {
      label = 'System Output';
      style = filled;
		  color = lightCyan;

      SUG [label = 'Course Suggestions']
      WAR [label = 'Warnings']
      PRE [label = 'Preparatory Coursework']
      }

      TR [label = 'Student´s Transcript']

      # Invisible node
      x2 [shape = circle, width = .01, height = .01, label = '']
      x3 [shape = circle, width = .01, height = .01, label = '']


      # edges

      SD -> AP [weight = 2];
      {SD, TM} -> TE;
      {TM, KW} -> AI;
      ID -> TR;
      {PM, CS, TR} -> GP;
      GP -> WAR;
		  WAR -> PRE;

      CD -> TM [label = '  LDA'];

      {AP, TE} -> x1 [arrowhead = none]
      x1 -> PM [label = '  Lasso'];
      
      {TM, AI} -> x2 [arrowhead = none]
      x2 -> SUG [label = '  KL distance'];

      {TM, PM} -> x3 [arrowhead = none]
      x3 -> PRE [label = '  KL distance'];

      }
      ")

# Save by hand
# image format: JPEG
# Width: 626
# Check Maintain aspect ratio
# File name: Conference/Figures/Flowchart
```

# Model Selection (topic model)

```{r}
max_LL <- df_logLike_catalogue$n_topic[which.max(df_logLike_catalogue$LogLikelihood)]

df_logLike_catalogue %>%
  ggplot(aes(x = n_topic, y = LogLikelihood)) +
  geom_vline(xintercept = max_LL, col = "red", alpha = 0.5, linetype = "dashed", size = 1) +
  geom_line(linetype = "dashed") +
  geom_point() +
  
  labs(title = "Model Selection", subtitle = str_c("The maximum-likelihood model has ", max_LL, " topics"), x = "Number of Topics", y = "Log-Likelihood") +

  ggsave(filename = str_c("Model Selection.jpeg"), path = output_folder,
         width = plot_width, height = plot_height)
```

# Beta

```{r plot_beta}
plot_beta <- function(topic = 1, sub = NULL, resize_factor = 1){
  
  top <-  str_c("Topic ", topic)
  
  beta %>%
    filter(topic == top) %>% 
    top_n(10, beta) %>%
    
    ggplot() +
    geom_col(aes(x = reorder(term, beta), y = beta)) +
    
    coord_flip() +
    
    theme(axis.text.y = element_text(size = 11)) +
    
    labs(title = str_c("Main Terms of ", top),
         subtitle = sub,
         x = "Terms",
         y = "Beta"
    )
  
  ggsave(filename = str_c("Beta - topic ", topic, ".jpeg"), path = output_folder,
         width = plot_width / resize_factor, height = plot_height / resize_factor)
  
}
```

```{r fig_beta}
# topic 1: engineering",
plot_beta(1, sub = "Topic 1 corresponds to the theme of engineering")
# topic 9: computer science, topic 
# Topic 20: psychology
# topic 25: history
# topic 26: literature 
```

# Gamma

```{r plot_gamma}
plot_gamma <- function(course = "COR1002", sub = NULL, course_title = course){
  
  gamma %>%
    filter(document == course) %>% 
    top_n(10, gamma) %>%
    
    ggplot() +
    geom_col(aes(x = reorder(topic, gamma), y = gamma)) +
    
    coord_flip() +
    
    labs(title    = str_c("Main Topics of Course ", course_title),
         subtitle = sub,
         x = "Topics",
         y = "Gamma"
         )
  
  ggsave(filename = str_c("gamma - course ", course, ".jpeg"), path = output_folder,
         width = plot_width, height = plot_height)
  
}
```

```{r fig_gamma}
plot_gamma("HUM1014", sub = "HUM1014 is dominated by topics 43 (philosophy) and 26 (literature)", course_title = "HUM1014 Great Novels 1850 - Present")

resize_factor <- 1.6

plot_beta(43, sub = "Theme of philosophy", resize_factor = resize_factor)

plot_beta(26, sub = "Theme of literature", resize_factor = resize_factor)
```


# Topic Expertise
```{r}
transcript <- tibble(Course    = paste("Course", 1:3),
                     Grade     = c(6  , 9  , 2.5))

gamma <- tibble(Course    = paste("Course", 1:3),
                `Topic 1` = c(0  , 0.2, 0.6),
                `Topic 2` = c(0.4, 0.2, 0.3),
                `Topic 3` = c(0  , 0.2, 0  ),
                `Topic 4` = c(0.4, 0.2, 0.1),
                `Topic 5` = c(0.2, 0.2, 0  ))

df1 <- gamma %>% 
  gather(key = Topic, value = gamma, -Course) %>% 
  arrange(Course) %>%
  
  left_join(transcript, by = "Course") %>%
  mutate(contribution = Grade/10 * gamma)

topic_expertise <- df1 %>%
  select(-gamma, - Grade) %>% 
  spread(key = Topic, value = contribution)

# Table

transcript %>% 
  mutate(Grade = str_c(Grade, "/10")) %>%
  kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/toy_transcript.pdf"))

gamma %>% 
  kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/toy_gamma.pdf"))

topic_expertise %>% 
  kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/toy_topic_expertise.pdf"))



# Plot
df1 %>% 
  ggplot(aes(x = Topic, y = contribution, fill = Course)) +
  geom_col() +
  labs(x = "Topics", y = "Topic Expertise", title = "Course Contribution towards Topic Expertise")

ggsave(filename = str_c("toy Topic Expertise.jpeg"), path = output_folder,
       width = plot_width, height = plot_height)
```


# CV
```{r}
fit_lasso %>%
  ggplot(aes(y = cv_error, group = 1)) +
  geom_boxplot() +
  theme(axis.ticks.x = element_line(color = "white"),
        axis.text.x = element_text(color = "white"),
        panel.border = element_rect(color = "white"),
        panel.grid = element_line(color = "white")
        ) +
  
  labs(title = "Distribution of Prediction Error", y = "Cross-Validation \n Mean Absolute Error")

ggsave(filename = str_c("CV.jpeg"), path = output_folder,
         width = plot_width/1.9, height = plot_height/1.2)

fit_lasso %>%
  summarize(Mean = mean(cv_error),
            `Weighted mean` = weighted.mean(cv_error, n),
            Median = median(cv_error),
            `Standard Deviation` = sd(cv_error),
            Minimum = min(cv_error),
            Maximum = max(cv_error)) %>%
  gather(key = x, value = y) %>% 
  kable("latex", booktabs = TRUE, col.names = NULL) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  as_image(file = str_c(output_folder, "/CV.pdf"))
```

