---
title: "Coherence"
author: "DARS"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r test set up}
library(textmineR)
library(Matrix)

load("Output/topic_model_gb.RDATA")

```
We need to import d_cast
#Just taking overview for 36 topics:
```{r coherence}
dtm <- d_cast$overview

#convert to sparse matrix
binDTM <- sparseMatrix(i = dtm$i, j = dtm$j, x = dtm$v, dims = c(dtm$nrow, dtm$ncol), dimnames = dimnames(dtm)) #from matrix

# Matrix multiplication for cooccurrence counts
coocCounts <- t(binDTM) %*% binDTM
coocCounts[1:5, 1:5]

term_topic_probability <- topic_model_gb$b_overview[[18]] # 36 topics

#coocurance matrix
coocurrance <- Dtm2Tcm(binDTM) #requires binDTM to be numeric matrix

as_tibble(coocurrance)

#inspect
coocurrance[1:5, 1:5]

#get top 5 words
top_words_topics <-  term_topic_probability %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  summarise(words = list(term))

# top words topic 1:
rows.to.keep <- which(rownames(coocurrance) %in% top_words_topics[1,]$words[[1]]) # matrix is squared same names for cols and rows

my_co <- coocurrance[rows.to.keep,rows.to.keep]

for(word in top_words_topics[1,]$words[[1]] ){
  score <- log((my_co[word, lag(word)]+1)/(my_co[word, word]*my_co[lag(word), lag(word)]))
}



CalcProbCoherence(phi = term_topic_probability, dtm = binDTM, M = 5)


pmap(.l = list(term_topic_probability), .f = CalcProbCoherence, dtm, 5)


coherence_UMas <- function(tf_idf) {
  tf_idf
  
}
```



