---
title: "Topic Scores"
author: "DARS"
date: "2/18/2019"
output: pdf_document
---
#Set up
##Libraries
```{r libraries}
library(tidyverse)
```
##Raw Data
```{r setup, include=FALSE}
#
##d_course and d_transcript
load("Output/data_pillar_1.RDATA")

#
##LDA_models
load("Output/LDA_overview.RDATA")

#
##Topic Models test for ideal number of topics
load("Output/LDA_ntopics_description.RDATA")
load("Output/LDA_ntopics_overview.RDATA")

```

## Getting Functions (gamma and beta) 
```{r getting functions}
get_beta <- function(results){
  
  tidy(results, matrix = "beta") %>%
    mutate(topic = paste("Topic", topic)) %>%
      arrange(topic, desc(beta))
  
}

get_gamma <- function(results){
  
  tidy(results, matrix = "gamma") %>%
    mutate(topic = paste("Topic", topic)) %>%
      arrange(topic, desc(gamma))
  
}

```

##Getting applied (gamma and beta) 
```{r getting beta and gamma}
# k=10, 20, 35
beta_description <- lapply(
  LDA_model,
  get_beta
)

gamma_descriptions <- lapply(
  LDA_model,
  get_gamma
)

```
##Inspect topics
```{r inspect topics}
topics <- beta_description$k35 %>%
  group_by(topic) %>%
  top_n(10, beta)

#
##View
View(topics)

```
## simulating students and key words
```{r student simulation}
terms <- unique(beta_description$k35$term)

student <- list()
student$kw_policy <- c("international", "economic", "conflict", "develop", "policy", "war", "philosophy") #sample(terms, 5)
student$kw_climate <- c("climate", "sustainability", "change", "development", "develop","sustain", "sustainable") #sample(terms, 5)
```

##getting top courses per student
```{r topic score student}
student$topic_score <- beta_description$k35 %>%
  filter(term %in% student$kw_policy)       %>%
  group_by(topic)                           %>% #maybe we can do this with transcripts afterwards
  summarize(B_score= sum(beta))             %>%
  ungroup()                                 %>%
  mutate(Total_b      = sum(B_score),
         B_proportion = B_score/Total_b)    %>%
  arrange(desc(B_score))

```

##Getting courses
```{r course_score}

student$course_score <- gamma_descriptions$k35     %>%
  full_join(student$topic_score, by = "topic")     %>%
  mutate(X = gamma * B_proportion)                 %>%
  group_by(document)                               %>%
  summarise(course_score = sum(X))                 %>%
  arrange(desc(course_score))                      %>%
  left_join(
    select(d_course, `Course ID`, `Course Title`),
    by = c("document" = "Course ID")
    )
```

###View
```{r View course}
View(student$topic_score)
View(student$course_score)
```

##Explaining outcome
###key words contribution to topic b_score
```{r topic score student}
#
## standardizing function (within topic)
standardize <- function (col) {
  col/sum(col)
}

#
##key word Contributions to Topic
 kw_to_topics <- beta_description$k35                                 %>%
  filter(term %in% student$kw_policy)                                 %>%
  arrange(topic, desc(beta))                                          %>%
  group_by(topic)                                                     %>%
  mutate(beta_sum=sum(beta),
         beta_rank=beta/beta_sum)                                     %>%
  select(-beta_sum, -beta)
```

###Topic contribution to course
```{r course_score}
#
##Extracts recommended courses n = 5
my_courses <- top_n(x = student$course_score, n = 5, wt =course_score) %>% 
  pull(document)

#
## Topic contribution to course
key_words <- gamma_descriptions$k35                             %>%
  filter(document %in% my_courses)                 %>%
  arrange(document, gamma)                         %>%
  full_join(kw_to_topics, by = "topic" ) %>%
  arrange(document, desc(gamma), desc(beta_rank) ) %>%
  group_by(document #, 
           #gamma
           )                                       %>%
  filter(row_number() %in% 1:3)                    %>%  #makes most sense with just 1 kw # group_by(document) %>% filter(row_number() %in% 1:9) 
  group_by(document)                               %>%
  summarise(key_words = list(Reduce(f= c,
                               x = term)))
```

##Selectig keywords
```{r}
top_kw <- beta_description$k35 %>%
  group_by(topic) %>%
  top_n(3, beta) %>%
  pull(term)

kw <- unique(top_kw)

kw_stopwords =c("student", "skill", "academic", "bate", "participant", "gain", "primarily", "main", "2016", "action", "level", "issue", "concept", "close", "day", "edition", "primary", "project", "method", "apply", "busy", "address", "role", "post", "oxford", "cuss", "lecture", "pbl",
    #unsure:
               "theory", "search", "perspective"
                )
kw <- setdiff(kw, kw_stopwords)
```

